/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyForwarder } from "./MyForwarder";
export * as factories from "./factories";
export { MyForwarder__factory } from "./factories/MyForwarder__factory";
